version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: 'weekly'
      timezone: 'America/Detroit'
      day: 'friday'
      time: '10:00'
    assignees:
      - "mitchfen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'weekly'
      timezone: 'America/Detroit'
      day: 'friday'
      time: '10:00'
    assignees:
      - "mitchfen"
